// Generated by Qodo Gen

import { isValid } from "../src/20.validParentheses";

describe('isValid', () => {

   // Valid string with matching pairs of parentheses '()' returns true
   it('should return true when string contains matching parentheses pairs', () => {
      const input = '()';
      const result = isValid(input);
      expect(result).toBe(true);
   });

   // Single opening bracket '(' returns false
   it('should return false when string contains single opening bracket', () => {
      const input = '(';
      const result = isValid(input);
      expect(result).toBe(false);
   });
   it('should return false when Unbalanced brackets with incorrect nesting', () => {
      const input = '([)]';
      const result = isValid(input);
      expect(result).toBe(false);
   });
   it('should return false when Unbalanced brackets with incorrect nesting', () => {
      const input = '()[]{}';
      const result = isValid(input);
      expect(result).toBe(true);
   });


});
